33| env:
34|   AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
35|   ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
36|   ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
37|   ECS_TASK ▋
